In [58]:
import pandas as pd

In [59]:
# 1. Create a DataFrame:
# Load the above dataset into a Pandas DataFrame.

sl = pd.DataFrame({'Order ID' : [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
                   'Customer' : ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Charlie', 'Bob', 'Alice'],
                   'Product' : ['Laptop', 'Phone', 'Chair', 'Table', 'Laptop', 'Phone', 'Chair', 'Phone'],
                   'Category' : ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Electronics', 'Electronics', 'Furniture', 'Electronics'],
                   'Quantity' : [2, 1, 4, 1, 1, 2, 2, 1],
                   'Price' : [800, 500, 100, 250, 800, 500, 100, 500],
                   'Total Sales' : [1600, 500, 400, 250, 800, 1000, 200, 500]})
sl

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500

In [60]:
# 2. Add a New Column:
# Add a column Discount that gives a 10% discount on total sales.

sl['Discount'] = sl['Total Sales'] * 0.10
sl

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

In [61]:
# 3. Add a New Row:
# Add a new sales record: Order ID = 1009, Customer =
# "Eve", Product = "Tablet", Category = "Electronics",
# Quantity = 1, Price = 300, Total Sales = 300.

sl.loc[len(sl)] = [1009, 'Eve', 'Tablet', 'Electronics', 1, 300, 300, 300 * 0.10]
sl

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Tablet,Electronics,1,300,300,30.0

In [62]:
# 4. Filter Data:
# Retrieve only the sales records where the Category is "Electronics".

s2 = sl.loc[sl['Category'] == 'Electronics']
s2

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
8,1009,Eve,Tablet,Electronics,1,300,300,30.0

In [63]:
# 5. Selection:
# Select the Customer and Total Sales columns.

s3 = sl[['Customer', 'Total Sales']]
s3

  Customer  Total Sales
0    Alice         1600
1      Bob          500
2  Charlie          400
3    Alice          250
4    David          800
5  Charlie         1000
6      Bob          200
7    Alice          500
8      Eve          300

In [64]:
# 6. Grouping:
# Group the data by Customer and calculate the total sales per customer.

grps = sl.groupby('Customer')['Total Sales'].sum()
grps

Customer
Alice      2350
Bob         700
Charlie    1400
David       800
Eve         300
Name: Total Sales, dtype: int64

In [65]:
# 7. Sorting:
# Sort the DataFrame based on Total Sales in descending order.

srt = sl.sort_values(by='Total Sales')
srt

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
6,1007,Bob,Chair,Furniture,2,100,200,20.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
8,1009,Eve,Tablet,Electronics,1,300,300,30.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0

In [66]:
# 8. Apply Function:
# Apply a lambda function to create a new column Sales Category,
# where values are labeled as "High" if Total Sales > 1000, otherwise "Low".
    
sl['Sales Category'] = sl['Total Sales'].apply(lambda x: 'High' if x > 750 else 'low')
sl

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,Sales Category
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0,High
1,1002,Bob,Phone,Electronics,1,500,500,50.0,low
2,1003,Charlie,Chair,Furniture,4,100,400,40.0,low
3,1004,Alice,Table,Furniture,1,250,250,25.0,low
4,1005,David,Laptop,Electronics,1,800,800,80.0,High
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0,High
6,1007,Bob,Chair,Furniture,2,100,200,20.0,low
7,1008,Alice,Phone,Electronics,1,500,500,50.0,low
8,1009,Eve,Tablet,Electronics,1,300,300,30.0,low

In [67]:
# 9. Save DataFrame:
# Save the final DataFrame as a CSV file named sales_data.csv.
sl.to_csv('sales_data.csv', index=False)